runtime: python
env: flex
# entrypoint: gunicorn main:app --timeout 300 --bind localhost:8080 --worker-class sanic.worker.GunicornWorker
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
    python_version: 3

resources:
  cpu: 1
  memory_gb: 0.6
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 2
  max_num_instances: 4

env_variables:
    REDIS_HOST: localhost
    REDIS_PORT: 6379